version: "3"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    privileged: true
    ports:
      - "0.0.0.0:18883:1883/tcp"
      - "0.0.0.0:9001:9001/tcp"
    volumes:
      - "./config:/mosquitto/config"
      - "./data:/mosquitto/data"
      - "./log:/mosquitto/log"
      - "./mosquitto.pwd:/etc/mosquitto/mosquitto.pwd"
