version: "3"

networks:
  nginx:
    name: nginx_network
    attachable: true

services:
  nginx:
    build: .
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./etc/ssl:/etc/nginx/ssl
      - ./etc/service-borodin.site.conf:/etc/nginx/service.conf
      # - ./etc/ssl:/etc/nginx/ssl
      # - ./etc/service-example.conf:/etc/nginx/service.conf
      # - ./etc/service-example-2.conf:/etc/nginx/service2.conf # more services, should be service*.conf
      # - ./etc/stream-example-2.conf:/etc/nginx/stream2.conf # more streams, should be stream*.conf
      # - ./etc/conf.d:/etc/nginx/conf.d-le # configuration folder, all files from it will be added
      # - ./etc/stream.conf:/etc/nginx/stream.conf.d-le # streams configuration folder, all files from it will be added
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=UTC
      - LETSENCRYPT=true
      - LE_EMAIL=dmitriy@borodin.site
      - LE_FQDN=borodin.site
      #- SSL_CERT=le-crt.pem
      #- SSL_KEY=le-key.pem
      #- SSL_CHAIN_CERT=le-chain-crt.pem
    networks:
      - nginx

  website:
    container_name: website
    image: borodindmitriy/borodin.site:eca9dbffae5a6a16c9020718405df3378dec700f
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    expose:
      - "3000"
    networks:
      - nginx
